export const products = [
  {
    id: 1,
    name: "Wireless Bluetooth Headphones",
    category: "Headphones",
    price: 49.99,
    description:
      "High-quality wireless headphones with Bluetooth connectivity.",
    image: "wireless_headphones.jpg",
    rating: 4.5,
  },
  {
    id: 2,
    name: "Fast Wireless Charger",
    category: "Chargers",
    price: 29.99,
    description:
      "Qi-enabled fast wireless charger for smartphones and other devices.",
    image: "fast_wireless_charger.jpg",
    rating: 4.0,
  },
  {
    id: 3,
    name: "Portable Power Bank",
    category: "Chargers",
    price: 19.99,
    description: "Compact and portable power bank for charging on the go.",
    image: "power_bank.jpg",
    rating: 4.2,
  },
  {
    id: 4,
    name: "Bluetooth Earbuds",
    category: "Headphones",
    price: 39.99,
    description:
      "Wireless earbuds with Bluetooth connectivity and noise cancellation.",
    image: "bluetooth_earbuds.jpg",
    rating: 4.7,
  },
  {
    id: 5,
    name: "Phone Stand Holder",
    category: "Accessories",
    price: 9.99,
    description: "Adjustable phone stand holder for hands-free use.",
    image: "phone_stand_holder.jpg",
    rating: 4.3,
  },
  {
    id: 6,
    name: "Car Phone Mount",
    category: "Accessories",
    price: 14.99,
    description:
      "Universal car phone mount for convenient navigation and hands-free calls.",
    image: "car_phone_mount.jpg",
    rating: 4.1,
  },
  {
    id: 7,
    name: "USB-C Charging Cable",
    category: "Cables",
    price: 8.99,
    description: "Durable USB-C charging cable for fast and reliable charging.",
    image: "usb_c_charging_cable.jpg",
    rating: 4.6,
  },
  {
    id: 8,
    name: "Wireless Gaming Mouse",
    category: "Accessories",
    price: 59.99,
    description: "Wireless gaming mouse with customizable RGB lighting.",
    image: "wireless_gaming_mouse.jpg",
    rating: 4.8,
  },
];
